version: "3.9"

services:
  battlesnake:
    image: sendwithus/battlesnake-server
    ports:
      - "3000:3000"

  znake-java:
    image: znake-java:latest
    build:
      context: .
      dockerfile: ./teams/znake-starter-springboot/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - battlesnake

  znake-node:
    image: znake-node:latest
    build:
      context: ./teams/znake-starter-node
      dockerfile: Dockerfile
    ports:
      - "9091:9090"
    depends_on:
      - battlesnake

  znake-go:
    image: znake-go:latest
    build:
      context: ./teams/znake-starter-go
      dockerfile: Dockerfile
    ports:
      - "9092:9090"
    depends_on:
      - battlesnake

  znake-python:
    image: znake-python:latest
    build:
      context: ./teams/znake-starter-python
      dockerfile: Dockerfile
    ports:
      - "9093:9090"
    depends_on:
      - battlesnake